---
version: '3.4'

services:
  etherpad:
    build: .
    ports:
      - "8080:9001"
    links:
      - "db"
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: etherpaduser
      MYSQL_PASSWORD: PASSWORD
      MYSQL_DATABASE: etherpad_lite_db

    ports:
      - "3306"
    volumes:
      - etherpad-db:/var/lib/mysql

volumes:
  etherpad-db:
